In [2]:
import torch

In [10]:
torch.tensor([1,3]).size() 

torch.Size([2])

In [23]:
torch.zeros([1,3]).squeeze(dim = 0)

tensor([0., 0., 0.])

In [14]:
torch.randn(2,3, 4,5,1)

tensor([[[[[ 1.2796],
           [ 0.5361],
           [-0.0193],
           [ 0.7238],
           [-1.0905]],

          [[-1.1332],
           [-0.4537],
           [-0.2331],
           [ 2.1415],
           [-1.6412]],

          [[ 0.4314],
           [ 0.0855],
           [ 0.9297],
           [-0.9285],
           [ 0.3398]],

          [[ 0.3370],
           [-0.2490],
           [ 1.6639],
           [ 0.1867],
           [ 1.7044]]],


         [[[-0.2864],
           [-0.0855],
           [-2.4374],
           [-0.9199],
           [ 0.1039]],

          [[-0.1260],
           [ 0.6233],
           [ 1.5205],
           [ 0.3956],
           [-0.6265]],

          [[-0.4307],
           [-1.2581],
           [-0.5345],
           [-0.7262],
           [ 1.8948]],

          [[-0.5235],
           [ 0.9657],
           [ 0.4700],
           [ 1.5786],
           [-1.5691]]],


         [[[-0.6227],
           [-0.1054],
           [ 0.6551],
           [-0.3779],
           [

In [18]:
torch.LongTensor([0,2])

tensor([0, 2])